/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CreateCustomer201,
  CreateCustomerRequest,
  ForbiddenResponse,
  GetCustomerById200,
  GetCustomers200,
  GetCustomersParams,
  InternalServerErrorResponse,
  NotFoundResponse,
  SuccessMessage,
  ToggleCustomerStatus200,
  ToggleStatusRequest,
  UnauthorizedResponse,
  UpdateCustomer200,
  UpdateCustomerRequest
} from '../model';

import { customInstance } from '.././http';




export type getCustomersResponse200 = {
  data: GetCustomers200
  status: 200
}

export type getCustomersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCustomersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getCustomersResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getCustomersResponseSuccess = (getCustomersResponse200) & {
  headers: Headers;
};
export type getCustomersResponseError = (getCustomersResponse401 | getCustomersResponse403 | getCustomersResponse500) & {
  headers: Headers;
};

export type getCustomersResponse = (getCustomersResponseSuccess | getCustomersResponseError)

export const getGetCustomersUrl = (params?: GetCustomersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/customers?${stringifiedParams}` : `/api/customers`
}

/**
 * Returns a paginated list of customers sorted by creation date. Searchable by name, phone, and email. Filterable by VIP status. Requires `view_customer` permission.
 * @summary List customers
 */
export const getCustomers = async (params?: GetCustomersParams, options?: RequestInit): Promise<getCustomersResponse> => {

  return customInstance<getCustomersResponse>(getGetCustomersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCustomersQueryKey = (params?: GetCustomersParams,) => {
    return [
    `/api/customers`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCustomersQueryOptions = <TData = Awaited<ReturnType<typeof getCustomers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(params?: GetCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCustomersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomers>>> = ({ signal }) => getCustomers(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCustomers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCustomersQueryResult = NonNullable<Awaited<ReturnType<typeof getCustomers>>>
export type GetCustomersQueryError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse


export function useGetCustomers<TData = Awaited<ReturnType<typeof getCustomers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params: undefined |  GetCustomersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomers>>,
          TError,
          Awaited<ReturnType<typeof getCustomers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomers<TData = Awaited<ReturnType<typeof getCustomers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomers>>,
          TError,
          Awaited<ReturnType<typeof getCustomers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomers<TData = Awaited<ReturnType<typeof getCustomers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List customers
 */

export function useGetCustomers<TData = Awaited<ReturnType<typeof getCustomers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetCustomersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomers>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCustomersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createCustomerResponse201 = {
  data: CreateCustomer201
  status: 201
}

export type createCustomerResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createCustomerResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createCustomerResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createCustomerResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createCustomerResponseSuccess = (createCustomerResponse201) & {
  headers: Headers;
};
export type createCustomerResponseError = (createCustomerResponse400 | createCustomerResponse401 | createCustomerResponse403 | createCustomerResponse500) & {
  headers: Headers;
};

export type createCustomerResponse = (createCustomerResponseSuccess | createCustomerResponseError)

export const getCreateCustomerUrl = () => {




  return `/api/customers`
}

/**
 * Creates a new customer. name and phone are required. Requires `create_customer` permission.
 * @summary Create a customer
 */
export const createCustomer = async (createCustomerRequest: CreateCustomerRequest, options?: RequestInit): Promise<createCustomerResponse> => {

  return customInstance<createCustomerResponse>(getCreateCustomerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCustomerRequest)
  }
);}




export const getCreateCustomerMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext> => {

const mutationKey = ['createCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createCustomer>>, {data: CreateCustomerRequest}> = (props) => {
          const {data} = props ?? {};

          return  createCustomer(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof createCustomer>>>
    export type CreateCustomerMutationBody = CreateCustomerRequest
    export type CreateCustomerMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse

    /**
 * @summary Create a customer
 */
export const useCreateCustomer = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createCustomer>>, TError,{data: CreateCustomerRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createCustomer>>,
        TError,
        {data: CreateCustomerRequest},
        TContext
      > => {
      return useMutation(getCreateCustomerMutationOptions(options), queryClient);
    }
    export type getCustomerByIdResponse200 = {
  data: GetCustomerById200
  status: 200
}

export type getCustomerByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getCustomerByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getCustomerByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getCustomerByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getCustomerByIdResponseSuccess = (getCustomerByIdResponse200) & {
  headers: Headers;
};
export type getCustomerByIdResponseError = (getCustomerByIdResponse401 | getCustomerByIdResponse403 | getCustomerByIdResponse404 | getCustomerByIdResponse500) & {
  headers: Headers;
};

export type getCustomerByIdResponse = (getCustomerByIdResponseSuccess | getCustomerByIdResponseError)

export const getGetCustomerByIdUrl = (id: string,) => {




  return `/api/customers/${id}`
}

/**
 * Retrieves a single customer. Requires `view_customer` permission.
 * @summary Get customer by ID
 */
export const getCustomerById = async (id: string, options?: RequestInit): Promise<getCustomerByIdResponse> => {

  return customInstance<getCustomerByIdResponse>(getGetCustomerByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCustomerByIdQueryKey = (id: string,) => {
    return [
    `/api/customers/${id}`
    ] as const;
    }


export const getGetCustomerByIdQueryOptions = <TData = Awaited<ReturnType<typeof getCustomerById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCustomerByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomerById>>> = ({ signal }) => getCustomerById(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCustomerByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCustomerById>>>
export type GetCustomerByIdQueryError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse


export function useGetCustomerById<TData = Awaited<ReturnType<typeof getCustomerById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomerById>>,
          TError,
          Awaited<ReturnType<typeof getCustomerById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomerById<TData = Awaited<ReturnType<typeof getCustomerById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomerById>>,
          TError,
          Awaited<ReturnType<typeof getCustomerById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomerById<TData = Awaited<ReturnType<typeof getCustomerById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get customer by ID
 */

export function useGetCustomerById<TData = Awaited<ReturnType<typeof getCustomerById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCustomerByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateCustomerResponse200 = {
  data: UpdateCustomer200
  status: 200
}

export type updateCustomerResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateCustomerResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateCustomerResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateCustomerResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateCustomerResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateCustomerResponseSuccess = (updateCustomerResponse200) & {
  headers: Headers;
};
export type updateCustomerResponseError = (updateCustomerResponse400 | updateCustomerResponse401 | updateCustomerResponse403 | updateCustomerResponse404 | updateCustomerResponse500) & {
  headers: Headers;
};

export type updateCustomerResponse = (updateCustomerResponseSuccess | updateCustomerResponseError)

export const getUpdateCustomerUrl = (id: string,) => {




  return `/api/customers/${id}`
}

/**
 * Partially or fully updates a customer. All fields optional. Requires `update_customer` permission.
 * @summary Update a customer
 */
export const updateCustomer = async (id: string,
    updateCustomerRequest: UpdateCustomerRequest, options?: RequestInit): Promise<updateCustomerResponse> => {

  return customInstance<updateCustomerResponse>(getUpdateCustomerUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateCustomerRequest)
  }
);}




export const getUpdateCustomerMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: string;data: UpdateCustomerRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: string;data: UpdateCustomerRequest}, TContext> => {

const mutationKey = ['updateCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCustomer>>, {id: string;data: UpdateCustomerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateCustomer(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof updateCustomer>>>
    export type UpdateCustomerMutationBody = UpdateCustomerRequest
    export type UpdateCustomerMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Update a customer
 */
export const useUpdateCustomer = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCustomer>>, TError,{id: string;data: UpdateCustomerRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCustomer>>,
        TError,
        {id: string;data: UpdateCustomerRequest},
        TContext
      > => {
      return useMutation(getUpdateCustomerMutationOptions(options), queryClient);
    }
    export type deleteCustomerResponse200 = {
  data: SuccessMessage
  status: 200
}

export type deleteCustomerResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteCustomerResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteCustomerResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteCustomerResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deleteCustomerResponseSuccess = (deleteCustomerResponse200) & {
  headers: Headers;
};
export type deleteCustomerResponseError = (deleteCustomerResponse401 | deleteCustomerResponse403 | deleteCustomerResponse404 | deleteCustomerResponse500) & {
  headers: Headers;
};

export type deleteCustomerResponse = (deleteCustomerResponseSuccess | deleteCustomerResponseError)

export const getDeleteCustomerUrl = (id: string,) => {




  return `/api/customers/${id}`
}

/**
 * Permanently deletes a customer. Requires `delete_customer` permission.
 * @summary Delete a customer
 */
export const deleteCustomer = async (id: string, options?: RequestInit): Promise<deleteCustomerResponse> => {

  return customInstance<deleteCustomerResponse>(getDeleteCustomerUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteCustomerMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomer>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCustomer>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteCustomer'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCustomer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteCustomer(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCustomer>>>

    export type DeleteCustomerMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a customer
 */
export const useDeleteCustomer = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomer>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCustomer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteCustomerMutationOptions(options), queryClient);
    }
    export type toggleCustomerStatusResponse200 = {
  data: ToggleCustomerStatus200
  status: 200
}

export type toggleCustomerStatusResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type toggleCustomerStatusResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type toggleCustomerStatusResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type toggleCustomerStatusResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type toggleCustomerStatusResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type toggleCustomerStatusResponseSuccess = (toggleCustomerStatusResponse200) & {
  headers: Headers;
};
export type toggleCustomerStatusResponseError = (toggleCustomerStatusResponse400 | toggleCustomerStatusResponse401 | toggleCustomerStatusResponse403 | toggleCustomerStatusResponse404 | toggleCustomerStatusResponse500) & {
  headers: Headers;
};

export type toggleCustomerStatusResponse = (toggleCustomerStatusResponseSuccess | toggleCustomerStatusResponseError)

export const getToggleCustomerStatusUrl = (id: string,) => {




  return `/api/customers/${id}/status`
}

/**
 * Sets the customer account status to 'active' or 'inactive'. Requires `update_customer` permission.
 * @summary Toggle customer status
 */
export const toggleCustomerStatus = async (id: string,
    toggleStatusRequest: ToggleStatusRequest, options?: RequestInit): Promise<toggleCustomerStatusResponse> => {

  return customInstance<toggleCustomerStatusResponse>(getToggleCustomerStatusUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(toggleStatusRequest)
  }
);}




export const getToggleCustomerStatusMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleCustomerStatus>>, TError,{id: string;data: ToggleStatusRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleCustomerStatus>>, TError,{id: string;data: ToggleStatusRequest}, TContext> => {

const mutationKey = ['toggleCustomerStatus'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleCustomerStatus>>, {id: string;data: ToggleStatusRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  toggleCustomerStatus(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToggleCustomerStatusMutationResult = NonNullable<Awaited<ReturnType<typeof toggleCustomerStatus>>>
    export type ToggleCustomerStatusMutationBody = ToggleStatusRequest
    export type ToggleCustomerStatusMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Toggle customer status
 */
export const useToggleCustomerStatus = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleCustomerStatus>>, TError,{id: string;data: ToggleStatusRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleCustomerStatus>>,
        TError,
        {id: string;data: ToggleStatusRequest},
        TContext
      > => {
      return useMutation(getToggleCustomerStatusMutationOptions(options), queryClient);
    }
