/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateReport201,
  CreateReportRequest,
  GetReportById200,
  GetReports200,
  GetReportsParams,
  InternalServerErrorResponse,
  NotFoundResponse,
  SuccessMessage,
  UnauthorizedResponse,
  UpdateReport200,
  UpdateReportRequest
} from '../model';

import { customInstance } from '.././http';




export type getReportsResponse200 = {
  data: GetReports200
  status: 200
}

export type getReportsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getReportsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getReportsResponseSuccess = (getReportsResponse200) & {
  headers: Headers;
};
export type getReportsResponseError = (getReportsResponse401 | getReportsResponse500) & {
  headers: Headers;
};

export type getReportsResponse = (getReportsResponseSuccess | getReportsResponseError)

export const getGetReportsUrl = (params?: GetReportsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reports?${stringifiedParams}` : `/api/reports`
}

/**
 * Returns a paginated list of reports, sorted by creation date. Searchable by title. Populates createdBy with user name and email. Authentication required.
 * @summary List reports
 */
export const getReports = async (params?: GetReportsParams, options?: RequestInit): Promise<getReportsResponse> => {

  return customInstance<getReportsResponse>(getGetReportsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReportsQueryKey = (params?: GetReportsParams,) => {
    return [
    `/api/reports`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetReportsQueryOptions = <TData = Awaited<ReturnType<typeof getReports>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(params?: GetReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReportsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReports>>> = ({ signal }) => getReports(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReportsQueryResult = NonNullable<Awaited<ReturnType<typeof getReports>>>
export type GetReportsQueryError = UnauthorizedResponse | InternalServerErrorResponse


export function useGetReports<TData = Awaited<ReturnType<typeof getReports>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
 params: undefined |  GetReportsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReports>>,
          TError,
          Awaited<ReturnType<typeof getReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReports<TData = Awaited<ReturnType<typeof getReports>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
 params?: GetReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReports>>,
          TError,
          Awaited<ReturnType<typeof getReports>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReports<TData = Awaited<ReturnType<typeof getReports>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
 params?: GetReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List reports
 */

export function useGetReports<TData = Awaited<ReturnType<typeof getReports>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
 params?: GetReportsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReports>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReportsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createReportResponse201 = {
  data: CreateReport201
  status: 201
}

export type createReportResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createReportResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createReportResponseSuccess = (createReportResponse201) & {
  headers: Headers;
};
export type createReportResponseError = (createReportResponse401 | createReportResponse500) & {
  headers: Headers;
};

export type createReportResponse = (createReportResponseSuccess | createReportResponseError)

export const getCreateReportUrl = () => {




  return `/api/reports`
}

/**
 * Creates a new report. The createdBy field is automatically set from the authenticated user's ID. Authentication required.
 * @summary Create a report
 */
export const createReport = async (createReportRequest: CreateReportRequest, options?: RequestInit): Promise<createReportResponse> => {

  return customInstance<createReportResponse>(getCreateReportUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createReportRequest)
  }
);}




export const getCreateReportMutationOptions = <TError = UnauthorizedResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{data: CreateReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{data: CreateReportRequest}, TContext> => {

const mutationKey = ['createReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReport>>, {data: CreateReportRequest}> = (props) => {
          const {data} = props ?? {};

          return  createReport(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateReportMutationResult = NonNullable<Awaited<ReturnType<typeof createReport>>>
    export type CreateReportMutationBody = CreateReportRequest
    export type CreateReportMutationError = UnauthorizedResponse | InternalServerErrorResponse

    /**
 * @summary Create a report
 */
export const useCreateReport = <TError = UnauthorizedResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReport>>, TError,{data: CreateReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReport>>,
        TError,
        {data: CreateReportRequest},
        TContext
      > => {
      return useMutation(getCreateReportMutationOptions(options), queryClient);
    }
    export type getReportByIdResponse200 = {
  data: GetReportById200
  status: 200
}

export type getReportByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getReportByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getReportByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getReportByIdResponseSuccess = (getReportByIdResponse200) & {
  headers: Headers;
};
export type getReportByIdResponseError = (getReportByIdResponse401 | getReportByIdResponse404 | getReportByIdResponse500) & {
  headers: Headers;
};

export type getReportByIdResponse = (getReportByIdResponseSuccess | getReportByIdResponseError)

export const getGetReportByIdUrl = (id: string,) => {




  return `/api/reports/${id}`
}

/**
 * Retrieves a single report with createdBy populated. Authentication required.
 * @summary Get report by ID
 */
export const getReportById = async (id: string, options?: RequestInit): Promise<getReportByIdResponse> => {

  return customInstance<getReportByIdResponse>(getGetReportByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetReportByIdQueryKey = (id: string,) => {
    return [
    `/api/reports/${id}`
    ] as const;
    }


export const getGetReportByIdQueryOptions = <TData = Awaited<ReturnType<typeof getReportById>>, TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReportById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReportByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReportById>>> = ({ signal }) => getReportById(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReportById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReportByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getReportById>>>
export type GetReportByIdQueryError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse


export function useGetReportById<TData = Awaited<ReturnType<typeof getReportById>>, TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReportById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportById>>,
          TError,
          Awaited<ReturnType<typeof getReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReportById<TData = Awaited<ReturnType<typeof getReportById>>, TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReportById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReportById>>,
          TError,
          Awaited<ReturnType<typeof getReportById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReportById<TData = Awaited<ReturnType<typeof getReportById>>, TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReportById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get report by ID
 */

export function useGetReportById<TData = Awaited<ReturnType<typeof getReportById>>, TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReportById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReportByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateReportResponse200 = {
  data: UpdateReport200
  status: 200
}

export type updateReportResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateReportResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateReportResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateReportResponseSuccess = (updateReportResponse200) & {
  headers: Headers;
};
export type updateReportResponseError = (updateReportResponse401 | updateReportResponse404 | updateReportResponse500) & {
  headers: Headers;
};

export type updateReportResponse = (updateReportResponseSuccess | updateReportResponseError)

export const getUpdateReportUrl = (id: string,) => {




  return `/api/reports/${id}`
}

/**
 * Fully or partially updates a report using req.body (all fields accepted). Authentication required.
 * @summary Update a report
 */
export const updateReport = async (id: string,
    updateReportRequest: UpdateReportRequest, options?: RequestInit): Promise<updateReportResponse> => {

  return customInstance<updateReportResponse>(getUpdateReportUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateReportRequest)
  }
);}




export const getUpdateReportMutationOptions = <TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReport>>, TError,{id: string;data: UpdateReportRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateReport>>, TError,{id: string;data: UpdateReportRequest}, TContext> => {

const mutationKey = ['updateReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateReport>>, {id: string;data: UpdateReportRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateReport(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateReportMutationResult = NonNullable<Awaited<ReturnType<typeof updateReport>>>
    export type UpdateReportMutationBody = UpdateReportRequest
    export type UpdateReportMutationError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Update a report
 */
export const useUpdateReport = <TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateReport>>, TError,{id: string;data: UpdateReportRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateReport>>,
        TError,
        {id: string;data: UpdateReportRequest},
        TContext
      > => {
      return useMutation(getUpdateReportMutationOptions(options), queryClient);
    }
    export type deleteReportResponse200 = {
  data: SuccessMessage
  status: 200
}

export type deleteReportResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteReportResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteReportResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deleteReportResponseSuccess = (deleteReportResponse200) & {
  headers: Headers;
};
export type deleteReportResponseError = (deleteReportResponse401 | deleteReportResponse404 | deleteReportResponse500) & {
  headers: Headers;
};

export type deleteReportResponse = (deleteReportResponseSuccess | deleteReportResponseError)

export const getDeleteReportUrl = (id: string,) => {




  return `/api/reports/${id}`
}

/**
 * Permanently deletes a report. Authentication required.
 * @summary Delete a report
 */
export const deleteReport = async (id: string, options?: RequestInit): Promise<deleteReportResponse> => {

  return customInstance<deleteReportResponse>(getDeleteReportUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteReportMutationOptions = <TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReport>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteReport>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteReport'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteReport>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteReport(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteReportMutationResult = NonNullable<Awaited<ReturnType<typeof deleteReport>>>

    export type DeleteReportMutationError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a report
 */
export const useDeleteReport = <TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteReport>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteReport>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteReportMutationOptions(options), queryClient);
    }
