/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateCategoryRequest,
  CreateMedicineCategory201,
  ForbiddenResponse,
  GetMedicineCategories200,
  GetMedicineCategoriesParams,
  GetMedicineCategoryById200,
  InternalServerErrorResponse,
  NotFoundResponse,
  SuccessMessage,
  UnauthorizedResponse,
  UpdateMedicineCategory200
} from '../model';

import { customInstance } from '.././http';




export type getMedicineCategoriesResponse200 = {
  data: GetMedicineCategories200
  status: 200
}

export type getMedicineCategoriesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMedicineCategoriesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMedicineCategoriesResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getMedicineCategoriesResponseSuccess = (getMedicineCategoriesResponse200) & {
  headers: Headers;
};
export type getMedicineCategoriesResponseError = (getMedicineCategoriesResponse401 | getMedicineCategoriesResponse403 | getMedicineCategoriesResponse500) & {
  headers: Headers;
};

export type getMedicineCategoriesResponse = (getMedicineCategoriesResponseSuccess | getMedicineCategoriesResponseError)

export const getGetMedicineCategoriesUrl = (params?: GetMedicineCategoriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/medicinesCategories?${stringifiedParams}` : `/api/medicinesCategories`
}

/**
 * Returns a paginated list of medicine categories. Searchable by name and description. Requires `view_category` permission.
 * @summary List medicine categories
 */
export const getMedicineCategories = async (params?: GetMedicineCategoriesParams, options?: RequestInit): Promise<getMedicineCategoriesResponse> => {

  return customInstance<getMedicineCategoriesResponse>(getGetMedicineCategoriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMedicineCategoriesQueryKey = (params?: GetMedicineCategoriesParams,) => {
    return [
    `/api/medicinesCategories`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMedicineCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getMedicineCategories>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(params?: GetMedicineCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategories>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMedicineCategoriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMedicineCategories>>> = ({ signal }) => getMedicineCategories(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMedicineCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getMedicineCategories>>>
export type GetMedicineCategoriesQueryError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse


export function useGetMedicineCategories<TData = Awaited<ReturnType<typeof getMedicineCategories>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params: undefined |  GetMedicineCategoriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMedicineCategories>>,
          TError,
          Awaited<ReturnType<typeof getMedicineCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMedicineCategories<TData = Awaited<ReturnType<typeof getMedicineCategories>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetMedicineCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMedicineCategories>>,
          TError,
          Awaited<ReturnType<typeof getMedicineCategories>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMedicineCategories<TData = Awaited<ReturnType<typeof getMedicineCategories>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetMedicineCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategories>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List medicine categories
 */

export function useGetMedicineCategories<TData = Awaited<ReturnType<typeof getMedicineCategories>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetMedicineCategoriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategories>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMedicineCategoriesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getMedicineCategoryByIdResponse200 = {
  data: GetMedicineCategoryById200
  status: 200
}

export type getMedicineCategoryByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMedicineCategoryByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMedicineCategoryByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMedicineCategoryByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getMedicineCategoryByIdResponseSuccess = (getMedicineCategoryByIdResponse200) & {
  headers: Headers;
};
export type getMedicineCategoryByIdResponseError = (getMedicineCategoryByIdResponse401 | getMedicineCategoryByIdResponse403 | getMedicineCategoryByIdResponse404 | getMedicineCategoryByIdResponse500) & {
  headers: Headers;
};

export type getMedicineCategoryByIdResponse = (getMedicineCategoryByIdResponseSuccess | getMedicineCategoryByIdResponseError)

export const getGetMedicineCategoryByIdUrl = (id: string,) => {




  return `/api/medicinesCategories/${id}`
}

/**
 * Retrieves a single medicine category. Requires `view_category` permission.
 * @summary Get category by ID
 */
export const getMedicineCategoryById = async (id: string, options?: RequestInit): Promise<getMedicineCategoryByIdResponse> => {

  return customInstance<getMedicineCategoryByIdResponse>(getGetMedicineCategoryByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMedicineCategoryByIdQueryKey = (id: string,) => {
    return [
    `/api/medicinesCategories/${id}`
    ] as const;
    }


export const getGetMedicineCategoryByIdQueryOptions = <TData = Awaited<ReturnType<typeof getMedicineCategoryById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategoryById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMedicineCategoryByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMedicineCategoryById>>> = ({ signal }) => getMedicineCategoryById(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategoryById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMedicineCategoryByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMedicineCategoryById>>>
export type GetMedicineCategoryByIdQueryError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse


export function useGetMedicineCategoryById<TData = Awaited<ReturnType<typeof getMedicineCategoryById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategoryById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMedicineCategoryById>>,
          TError,
          Awaited<ReturnType<typeof getMedicineCategoryById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMedicineCategoryById<TData = Awaited<ReturnType<typeof getMedicineCategoryById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategoryById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMedicineCategoryById>>,
          TError,
          Awaited<ReturnType<typeof getMedicineCategoryById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMedicineCategoryById<TData = Awaited<ReturnType<typeof getMedicineCategoryById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategoryById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get category by ID
 */

export function useGetMedicineCategoryById<TData = Awaited<ReturnType<typeof getMedicineCategoryById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineCategoryById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMedicineCategoryByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createMedicineCategoryResponse201 = {
  data: CreateMedicineCategory201
  status: 201
}

export type createMedicineCategoryResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createMedicineCategoryResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createMedicineCategoryResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createMedicineCategoryResponseSuccess = (createMedicineCategoryResponse201) & {
  headers: Headers;
};
export type createMedicineCategoryResponseError = (createMedicineCategoryResponse401 | createMedicineCategoryResponse403 | createMedicineCategoryResponse500) & {
  headers: Headers;
};

export type createMedicineCategoryResponse = (createMedicineCategoryResponseSuccess | createMedicineCategoryResponseError)

export const getCreateMedicineCategoryUrl = () => {




  return `/api/medicinesCategories/create`
}

/**
 * Creates a new medicine category with a name and description. Requires `create_category` permission.
 * @summary Create a medicine category
 */
export const createMedicineCategory = async (createCategoryRequest: CreateCategoryRequest, options?: RequestInit): Promise<createMedicineCategoryResponse> => {

  return customInstance<createMedicineCategoryResponse>(getCreateMedicineCategoryUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCategoryRequest)
  }
);}




export const getCreateMedicineCategoryMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMedicineCategory>>, TError,{data: CreateCategoryRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMedicineCategory>>, TError,{data: CreateCategoryRequest}, TContext> => {

const mutationKey = ['createMedicineCategory'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMedicineCategory>>, {data: CreateCategoryRequest}> = (props) => {
          const {data} = props ?? {};

          return  createMedicineCategory(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMedicineCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof createMedicineCategory>>>
    export type CreateMedicineCategoryMutationBody = CreateCategoryRequest
    export type CreateMedicineCategoryMutationError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse

    /**
 * @summary Create a medicine category
 */
export const useCreateMedicineCategory = <TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMedicineCategory>>, TError,{data: CreateCategoryRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMedicineCategory>>,
        TError,
        {data: CreateCategoryRequest},
        TContext
      > => {
      return useMutation(getCreateMedicineCategoryMutationOptions(options), queryClient);
    }
    export type updateMedicineCategoryResponse200 = {
  data: UpdateMedicineCategory200
  status: 200
}

export type updateMedicineCategoryResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateMedicineCategoryResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateMedicineCategoryResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateMedicineCategoryResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateMedicineCategoryResponseSuccess = (updateMedicineCategoryResponse200) & {
  headers: Headers;
};
export type updateMedicineCategoryResponseError = (updateMedicineCategoryResponse401 | updateMedicineCategoryResponse403 | updateMedicineCategoryResponse404 | updateMedicineCategoryResponse500) & {
  headers: Headers;
};

export type updateMedicineCategoryResponse = (updateMedicineCategoryResponseSuccess | updateMedicineCategoryResponseError)

export const getUpdateMedicineCategoryUrl = (id: string,) => {




  return `/api/medicinesCategories/update/${id}`
}

/**
 * Updates name and/or description of a medicine category. Requires `update_category` permission.
 * @summary Update a medicine category
 */
export const updateMedicineCategory = async (id: string,
    createCategoryRequest: CreateCategoryRequest, options?: RequestInit): Promise<updateMedicineCategoryResponse> => {

  return customInstance<updateMedicineCategoryResponse>(getUpdateMedicineCategoryUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createCategoryRequest)
  }
);}




export const getUpdateMedicineCategoryMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMedicineCategory>>, TError,{id: string;data: CreateCategoryRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMedicineCategory>>, TError,{id: string;data: CreateCategoryRequest}, TContext> => {

const mutationKey = ['updateMedicineCategory'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMedicineCategory>>, {id: string;data: CreateCategoryRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMedicineCategory(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMedicineCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof updateMedicineCategory>>>
    export type UpdateMedicineCategoryMutationBody = CreateCategoryRequest
    export type UpdateMedicineCategoryMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Update a medicine category
 */
export const useUpdateMedicineCategory = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMedicineCategory>>, TError,{id: string;data: CreateCategoryRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMedicineCategory>>,
        TError,
        {id: string;data: CreateCategoryRequest},
        TContext
      > => {
      return useMutation(getUpdateMedicineCategoryMutationOptions(options), queryClient);
    }
    export type deleteMedicineCategoryResponse200 = {
  data: SuccessMessage
  status: 200
}

export type deleteMedicineCategoryResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteMedicineCategoryResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteMedicineCategoryResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteMedicineCategoryResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deleteMedicineCategoryResponseSuccess = (deleteMedicineCategoryResponse200) & {
  headers: Headers;
};
export type deleteMedicineCategoryResponseError = (deleteMedicineCategoryResponse401 | deleteMedicineCategoryResponse403 | deleteMedicineCategoryResponse404 | deleteMedicineCategoryResponse500) & {
  headers: Headers;
};

export type deleteMedicineCategoryResponse = (deleteMedicineCategoryResponseSuccess | deleteMedicineCategoryResponseError)

export const getDeleteMedicineCategoryUrl = (id: string,) => {




  return `/api/medicinesCategories/delete/${id}`
}

/**
 * Permanently deletes a medicine category. Requires `delete_category` permission.
 * @summary Delete a medicine category
 */
export const deleteMedicineCategory = async (id: string, options?: RequestInit): Promise<deleteMedicineCategoryResponse> => {

  return customInstance<deleteMedicineCategoryResponse>(getDeleteMedicineCategoryUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteMedicineCategoryMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMedicineCategory>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMedicineCategory>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMedicineCategory'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMedicineCategory>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMedicineCategory(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMedicineCategoryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMedicineCategory>>>

    export type DeleteMedicineCategoryMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a medicine category
 */
export const useDeleteMedicineCategory = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMedicineCategory>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMedicineCategory>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteMedicineCategoryMutationOptions(options), queryClient);
    }
