/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSale201,
  CreateSaleRequest,
  ForbiddenResponse,
  GetSaleById200,
  GetSales200,
  GetSalesParams,
  InternalServerErrorResponse,
  NotFoundResponse,
  SuccessMessage,
  UnauthorizedResponse,
  UpdateSale200,
  UpdateSaleRequest
} from '../model';

import { customInstance } from '.././http';




export type getSalesResponse200 = {
  data: GetSales200
  status: 200
}

export type getSalesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSalesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getSalesResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getSalesResponseSuccess = (getSalesResponse200) & {
  headers: Headers;
};
export type getSalesResponseError = (getSalesResponse401 | getSalesResponse403 | getSalesResponse500) & {
  headers: Headers;
};

export type getSalesResponse = (getSalesResponseSuccess | getSalesResponseError)

export const getGetSalesUrl = (params?: GetSalesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/sales?${stringifiedParams}` : `/api/sales`
}

/**
 * Returns a paginated list of sale invoices. Searchable by invoiceNumber, customerName, medicineName, and paymentMethod. Requires `view_sale` permission.
 * @summary List sales
 */
export const getSales = async (params?: GetSalesParams, options?: RequestInit): Promise<getSalesResponse> => {

  return customInstance<getSalesResponse>(getGetSalesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSalesQueryKey = (params?: GetSalesParams,) => {
    return [
    `/api/sales`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSalesQueryOptions = <TData = Awaited<ReturnType<typeof getSales>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(params?: GetSalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSales>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSalesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSales>>> = ({ signal }) => getSales(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSales>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSalesQueryResult = NonNullable<Awaited<ReturnType<typeof getSales>>>
export type GetSalesQueryError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse


export function useGetSales<TData = Awaited<ReturnType<typeof getSales>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params: undefined |  GetSalesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSales>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSales>>,
          TError,
          Awaited<ReturnType<typeof getSales>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSales<TData = Awaited<ReturnType<typeof getSales>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetSalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSales>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSales>>,
          TError,
          Awaited<ReturnType<typeof getSales>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSales<TData = Awaited<ReturnType<typeof getSales>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetSalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSales>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List sales
 */

export function useGetSales<TData = Awaited<ReturnType<typeof getSales>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetSalesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSales>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSalesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createSaleResponse201 = {
  data: CreateSale201
  status: 201
}

export type createSaleResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createSaleResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createSaleResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createSaleResponseSuccess = (createSaleResponse201) & {
  headers: Headers;
};
export type createSaleResponseError = (createSaleResponse401 | createSaleResponse403 | createSaleResponse500) & {
  headers: Headers;
};

export type createSaleResponse = (createSaleResponseSuccess | createSaleResponseError)

export const getCreateSaleUrl = () => {




  return `/api/sales`
}

/**
 * Records a new sale/invoice. Requires `create_sale` permission.
 * @summary Create a sale
 */
export const createSale = async (createSaleRequest: CreateSaleRequest, options?: RequestInit): Promise<createSaleResponse> => {

  return customInstance<createSaleResponse>(getCreateSaleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSaleRequest)
  }
);}




export const getCreateSaleMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSale>>, TError,{data: CreateSaleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createSale>>, TError,{data: CreateSaleRequest}, TContext> => {

const mutationKey = ['createSale'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSale>>, {data: CreateSaleRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSale(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSaleMutationResult = NonNullable<Awaited<ReturnType<typeof createSale>>>
    export type CreateSaleMutationBody = CreateSaleRequest
    export type CreateSaleMutationError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse

    /**
 * @summary Create a sale
 */
export const useCreateSale = <TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSale>>, TError,{data: CreateSaleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSale>>,
        TError,
        {data: CreateSaleRequest},
        TContext
      > => {
      return useMutation(getCreateSaleMutationOptions(options), queryClient);
    }
    export type getSaleByIdResponse200 = {
  data: GetSaleById200
  status: 200
}

export type getSaleByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSaleByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getSaleByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getSaleByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getSaleByIdResponseSuccess = (getSaleByIdResponse200) & {
  headers: Headers;
};
export type getSaleByIdResponseError = (getSaleByIdResponse401 | getSaleByIdResponse403 | getSaleByIdResponse404 | getSaleByIdResponse500) & {
  headers: Headers;
};

export type getSaleByIdResponse = (getSaleByIdResponseSuccess | getSaleByIdResponseError)

export const getGetSaleByIdUrl = (id: string,) => {




  return `/api/sales/${id}`
}

/**
 * Retrieves a single sale. Requires `view_sale` permission.
 * @summary Get sale by ID
 */
export const getSaleById = async (id: string, options?: RequestInit): Promise<getSaleByIdResponse> => {

  return customInstance<getSaleByIdResponse>(getGetSaleByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSaleByIdQueryKey = (id: string,) => {
    return [
    `/api/sales/${id}`
    ] as const;
    }


export const getGetSaleByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSaleById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSaleByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSaleById>>> = ({ signal }) => getSaleById(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSaleByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSaleById>>>
export type GetSaleByIdQueryError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse


export function useGetSaleById<TData = Awaited<ReturnType<typeof getSaleById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaleById>>,
          TError,
          Awaited<ReturnType<typeof getSaleById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSaleById<TData = Awaited<ReturnType<typeof getSaleById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaleById>>,
          TError,
          Awaited<ReturnType<typeof getSaleById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSaleById<TData = Awaited<ReturnType<typeof getSaleById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get sale by ID
 */

export function useGetSaleById<TData = Awaited<ReturnType<typeof getSaleById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaleById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSaleByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateSaleResponse200 = {
  data: UpdateSale200
  status: 200
}

export type updateSaleResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateSaleResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateSaleResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateSaleResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateSaleResponseSuccess = (updateSaleResponse200) & {
  headers: Headers;
};
export type updateSaleResponseError = (updateSaleResponse401 | updateSaleResponse403 | updateSaleResponse404 | updateSaleResponse500) & {
  headers: Headers;
};

export type updateSaleResponse = (updateSaleResponseSuccess | updateSaleResponseError)

export const getUpdateSaleUrl = (id: string,) => {




  return `/api/sales/${id}`
}

/**
 * Updates a sale record using $set (partial update). Requires `update_sale` permission.
 * @summary Update a sale
 */
export const updateSale = async (id: string,
    updateSaleRequest: UpdateSaleRequest, options?: RequestInit): Promise<updateSaleResponse> => {

  return customInstance<updateSaleResponse>(getUpdateSaleUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSaleRequest)
  }
);}




export const getUpdateSaleMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSale>>, TError,{id: string;data: UpdateSaleRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSale>>, TError,{id: string;data: UpdateSaleRequest}, TContext> => {

const mutationKey = ['updateSale'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSale>>, {id: string;data: UpdateSaleRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSale(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSaleMutationResult = NonNullable<Awaited<ReturnType<typeof updateSale>>>
    export type UpdateSaleMutationBody = UpdateSaleRequest
    export type UpdateSaleMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Update a sale
 */
export const useUpdateSale = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSale>>, TError,{id: string;data: UpdateSaleRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSale>>,
        TError,
        {id: string;data: UpdateSaleRequest},
        TContext
      > => {
      return useMutation(getUpdateSaleMutationOptions(options), queryClient);
    }
    export type deleteSaleResponse200 = {
  data: SuccessMessage
  status: 200
}

export type deleteSaleResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteSaleResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteSaleResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteSaleResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deleteSaleResponseSuccess = (deleteSaleResponse200) & {
  headers: Headers;
};
export type deleteSaleResponseError = (deleteSaleResponse401 | deleteSaleResponse403 | deleteSaleResponse404 | deleteSaleResponse500) & {
  headers: Headers;
};

export type deleteSaleResponse = (deleteSaleResponseSuccess | deleteSaleResponseError)

export const getDeleteSaleUrl = (id: string,) => {




  return `/api/sales/${id}`
}

/**
 * Permanently deletes a sale record. Requires `delete_sale` permission.
 * @summary Delete a sale
 */
export const deleteSale = async (id: string, options?: RequestInit): Promise<deleteSaleResponse> => {

  return customInstance<deleteSaleResponse>(getDeleteSaleUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSaleMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSale>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteSale>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteSale'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSale>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteSale(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSaleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSale>>>

    export type DeleteSaleMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a sale
 */
export const useDeleteSale = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSale>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSale>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteSaleMutationOptions(options), queryClient);
    }
