/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateMedicine201,
  CreateMedicineRequest,
  ForbiddenResponse,
  GetMedicines200,
  GetMedicinesParams,
  InternalServerErrorResponse,
  Medicine,
  NotFoundResponse,
  SuccessMessage,
  UnauthorizedResponse,
  UpdateMedicineRequest
} from '../model';

import { customInstance } from '.././http';




export type getMedicinesResponse200 = {
  data: GetMedicines200
  status: 200
}

export type getMedicinesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMedicinesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMedicinesResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getMedicinesResponseSuccess = (getMedicinesResponse200) & {
  headers: Headers;
};
export type getMedicinesResponseError = (getMedicinesResponse401 | getMedicinesResponse403 | getMedicinesResponse500) & {
  headers: Headers;
};

export type getMedicinesResponse = (getMedicinesResponseSuccess | getMedicinesResponseError)

export const getGetMedicinesUrl = (params?: GetMedicinesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/medicines?${stringifiedParams}` : `/api/medicines`
}

/**
 * Paginated list of medicines. Search is performed across name, category, and supplier fields. Requires `view_store` permission.
 * @summary List medicines
 */
export const getMedicines = async (params?: GetMedicinesParams, options?: RequestInit): Promise<getMedicinesResponse> => {

  return customInstance<getMedicinesResponse>(getGetMedicinesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMedicinesQueryKey = (params?: GetMedicinesParams,) => {
    return [
    `/api/medicines`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMedicinesQueryOptions = <TData = Awaited<ReturnType<typeof getMedicines>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(params?: GetMedicinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicines>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMedicinesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMedicines>>> = ({ signal }) => getMedicines(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMedicines>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMedicinesQueryResult = NonNullable<Awaited<ReturnType<typeof getMedicines>>>
export type GetMedicinesQueryError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse


export function useGetMedicines<TData = Awaited<ReturnType<typeof getMedicines>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params: undefined |  GetMedicinesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicines>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMedicines>>,
          TError,
          Awaited<ReturnType<typeof getMedicines>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMedicines<TData = Awaited<ReturnType<typeof getMedicines>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetMedicinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicines>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMedicines>>,
          TError,
          Awaited<ReturnType<typeof getMedicines>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMedicines<TData = Awaited<ReturnType<typeof getMedicines>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetMedicinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicines>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List medicines
 */

export function useGetMedicines<TData = Awaited<ReturnType<typeof getMedicines>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetMedicinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicines>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMedicinesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createMedicineResponse201 = {
  data: CreateMedicine201
  status: 201
}

export type createMedicineResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createMedicineResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createMedicineResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createMedicineResponseSuccess = (createMedicineResponse201) & {
  headers: Headers;
};
export type createMedicineResponseError = (createMedicineResponse401 | createMedicineResponse403 | createMedicineResponse500) & {
  headers: Headers;
};

export type createMedicineResponse = (createMedicineResponseSuccess | createMedicineResponseError)

export const getCreateMedicineUrl = () => {




  return `/api/medicines`
}

/**
 * Creates a new medicine entry. Image is uploaded to Cloudinary via multipart/form-data. Requires `create_store` permission.
 * @summary Create a medicine
 */
export const createMedicine = async (createMedicineRequest: CreateMedicineRequest, options?: RequestInit): Promise<createMedicineResponse> => {
    const formData = new FormData();
formData.append(`name`, createMedicineRequest.name);
formData.append(`category`, createMedicineRequest.category);
formData.append(`quantity`, createMedicineRequest.quantity.toString())
formData.append(`price`, createMedicineRequest.price.toString())
formData.append(`expiryDate`, createMedicineRequest.expiryDate);
formData.append(`supplier`, createMedicineRequest.supplier);
formData.append(`storeStatus`, createMedicineRequest.storeStatus);
if(createMedicineRequest.image !== undefined) {
 formData.append(`image`, createMedicineRequest.image);
 }

  return customInstance<createMedicineResponse>(getCreateMedicineUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
);}




export const getCreateMedicineMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMedicine>>, TError,{data: CreateMedicineRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMedicine>>, TError,{data: CreateMedicineRequest}, TContext> => {

const mutationKey = ['createMedicine'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMedicine>>, {data: CreateMedicineRequest}> = (props) => {
          const {data} = props ?? {};

          return  createMedicine(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMedicineMutationResult = NonNullable<Awaited<ReturnType<typeof createMedicine>>>
    export type CreateMedicineMutationBody = CreateMedicineRequest
    export type CreateMedicineMutationError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse

    /**
 * @summary Create a medicine
 */
export const useCreateMedicine = <TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMedicine>>, TError,{data: CreateMedicineRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMedicine>>,
        TError,
        {data: CreateMedicineRequest},
        TContext
      > => {
      return useMutation(getCreateMedicineMutationOptions(options), queryClient);
    }
    export type getMedicineByIdResponse200 = {
  data: Medicine
  status: 200
}

export type getMedicineByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getMedicineByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMedicineByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMedicineByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getMedicineByIdResponseSuccess = (getMedicineByIdResponse200) & {
  headers: Headers;
};
export type getMedicineByIdResponseError = (getMedicineByIdResponse401 | getMedicineByIdResponse403 | getMedicineByIdResponse404 | getMedicineByIdResponse500) & {
  headers: Headers;
};

export type getMedicineByIdResponse = (getMedicineByIdResponseSuccess | getMedicineByIdResponseError)

export const getGetMedicineByIdUrl = (id: string,) => {




  return `/api/medicines/${id}`
}

/**
 * Retrieves a single medicine. Requires `view_store` permission.
 * @summary Get medicine by ID
 */
export const getMedicineById = async (id: string, options?: RequestInit): Promise<getMedicineByIdResponse> => {

  return customInstance<getMedicineByIdResponse>(getGetMedicineByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMedicineByIdQueryKey = (id: string,) => {
    return [
    `/api/medicines/${id}`
    ] as const;
    }


export const getGetMedicineByIdQueryOptions = <TData = Awaited<ReturnType<typeof getMedicineById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMedicineByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMedicineById>>> = ({ signal }) => getMedicineById(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMedicineById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMedicineByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMedicineById>>>
export type GetMedicineByIdQueryError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse


export function useGetMedicineById<TData = Awaited<ReturnType<typeof getMedicineById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMedicineById>>,
          TError,
          Awaited<ReturnType<typeof getMedicineById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMedicineById<TData = Awaited<ReturnType<typeof getMedicineById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMedicineById>>,
          TError,
          Awaited<ReturnType<typeof getMedicineById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMedicineById<TData = Awaited<ReturnType<typeof getMedicineById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get medicine by ID
 */

export function useGetMedicineById<TData = Awaited<ReturnType<typeof getMedicineById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMedicineById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMedicineByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateMedicineResponse200 = {
  data: Medicine
  status: 200
}

export type updateMedicineResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateMedicineResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateMedicineResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateMedicineResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateMedicineResponseSuccess = (updateMedicineResponse200) & {
  headers: Headers;
};
export type updateMedicineResponseError = (updateMedicineResponse401 | updateMedicineResponse403 | updateMedicineResponse404 | updateMedicineResponse500) & {
  headers: Headers;
};

export type updateMedicineResponse = (updateMedicineResponseSuccess | updateMedicineResponseError)

export const getUpdateMedicineUrl = (id: string,) => {




  return `/api/medicines/${id}`
}

/**
 * Updates medicine fields. Replaces old Cloudinary image if a new one is provided. Requires `update_store` permission.
 * @summary Update a medicine
 */
export const updateMedicine = async (id: string,
    updateMedicineRequest: UpdateMedicineRequest, options?: RequestInit): Promise<updateMedicineResponse> => {
    const formData = new FormData();
if(updateMedicineRequest.name !== undefined) {
 formData.append(`name`, updateMedicineRequest.name);
 }
if(updateMedicineRequest.category !== undefined) {
 formData.append(`category`, updateMedicineRequest.category);
 }
if(updateMedicineRequest.quantity !== undefined) {
 formData.append(`quantity`, updateMedicineRequest.quantity.toString())
 }
if(updateMedicineRequest.price !== undefined) {
 formData.append(`price`, updateMedicineRequest.price.toString())
 }
if(updateMedicineRequest.expiryDate !== undefined) {
 formData.append(`expiryDate`, updateMedicineRequest.expiryDate);
 }
if(updateMedicineRequest.supplier !== undefined) {
 formData.append(`supplier`, updateMedicineRequest.supplier);
 }
if(updateMedicineRequest.storeStatus !== undefined) {
 formData.append(`storeStatus`, updateMedicineRequest.storeStatus);
 }
if(updateMedicineRequest.image !== undefined) {
 formData.append(`image`, updateMedicineRequest.image);
 }

  return customInstance<updateMedicineResponse>(getUpdateMedicineUrl(id),
  {
    ...options,
    method: 'PUT'
    ,
    body: formData
  }
);}




export const getUpdateMedicineMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMedicine>>, TError,{id: string;data: UpdateMedicineRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateMedicine>>, TError,{id: string;data: UpdateMedicineRequest}, TContext> => {

const mutationKey = ['updateMedicine'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMedicine>>, {id: string;data: UpdateMedicineRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMedicine(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMedicineMutationResult = NonNullable<Awaited<ReturnType<typeof updateMedicine>>>
    export type UpdateMedicineMutationBody = UpdateMedicineRequest
    export type UpdateMedicineMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Update a medicine
 */
export const useUpdateMedicine = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMedicine>>, TError,{id: string;data: UpdateMedicineRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMedicine>>,
        TError,
        {id: string;data: UpdateMedicineRequest},
        TContext
      > => {
      return useMutation(getUpdateMedicineMutationOptions(options), queryClient);
    }
    export type deleteMedicineResponse200 = {
  data: SuccessMessage
  status: 200
}

export type deleteMedicineResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteMedicineResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteMedicineResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteMedicineResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deleteMedicineResponseSuccess = (deleteMedicineResponse200) & {
  headers: Headers;
};
export type deleteMedicineResponseError = (deleteMedicineResponse401 | deleteMedicineResponse403 | deleteMedicineResponse404 | deleteMedicineResponse500) & {
  headers: Headers;
};

export type deleteMedicineResponse = (deleteMedicineResponseSuccess | deleteMedicineResponseError)

export const getDeleteMedicineUrl = (id: string,) => {




  return `/api/medicines/${id}`
}

/**
 * Deletes a medicine and removes its image from Cloudinary. Requires `delete_store` permission.
 * @summary Delete a medicine
 */
export const deleteMedicine = async (id: string, options?: RequestInit): Promise<deleteMedicineResponse> => {

  return customInstance<deleteMedicineResponse>(getDeleteMedicineUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteMedicineMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMedicine>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMedicine>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMedicine'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMedicine>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMedicine(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMedicineMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMedicine>>>

    export type DeleteMedicineMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a medicine
 */
export const useDeleteMedicine = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMedicine>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMedicine>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteMedicineMutationOptions(options), queryClient);
    }
