/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CreateSupplier201,
  CreateSupplierRequest,
  ForbiddenResponse,
  GetSupplierById200,
  GetSuppliers200,
  GetSuppliersParams,
  InternalServerErrorResponse,
  NotFoundResponse,
  SuccessMessage,
  ToggleStatusRequest,
  ToggleSupplierStatus200,
  UnauthorizedResponse,
  UpdateSupplier200,
  UpdateSupplierRequest
} from '../model';

import { customInstance } from '.././http';




export type getSuppliersResponse200 = {
  data: GetSuppliers200
  status: 200
}

export type getSuppliersResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSuppliersResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getSuppliersResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getSuppliersResponseSuccess = (getSuppliersResponse200) & {
  headers: Headers;
};
export type getSuppliersResponseError = (getSuppliersResponse401 | getSuppliersResponse403 | getSuppliersResponse500) & {
  headers: Headers;
};

export type getSuppliersResponse = (getSuppliersResponseSuccess | getSuppliersResponseError)

export const getGetSuppliersUrl = (params?: GetSuppliersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/suppliers?${stringifiedParams}` : `/api/suppliers`
}

/**
 * Returns a paginated list of suppliers sorted by creation date (newest first). Searchable by name, phone, email, and address. Filterable by paymentType. Requires `view_supplier` permission.
 * @summary List suppliers
 */
export const getSuppliers = async (params?: GetSuppliersParams, options?: RequestInit): Promise<getSuppliersResponse> => {

  return customInstance<getSuppliersResponse>(getGetSuppliersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSuppliersQueryKey = (params?: GetSuppliersParams,) => {
    return [
    `/api/suppliers`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSuppliersQueryOptions = <TData = Awaited<ReturnType<typeof getSuppliers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(params?: GetSuppliersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuppliers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSuppliersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSuppliers>>> = ({ signal }) => getSuppliers(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSuppliers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSuppliersQueryResult = NonNullable<Awaited<ReturnType<typeof getSuppliers>>>
export type GetSuppliersQueryError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse


export function useGetSuppliers<TData = Awaited<ReturnType<typeof getSuppliers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params: undefined |  GetSuppliersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuppliers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSuppliers>>,
          TError,
          Awaited<ReturnType<typeof getSuppliers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuppliers<TData = Awaited<ReturnType<typeof getSuppliers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetSuppliersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuppliers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSuppliers>>,
          TError,
          Awaited<ReturnType<typeof getSuppliers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuppliers<TData = Awaited<ReturnType<typeof getSuppliers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetSuppliersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuppliers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List suppliers
 */

export function useGetSuppliers<TData = Awaited<ReturnType<typeof getSuppliers>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetSuppliersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuppliers>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSuppliersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createSupplierResponse201 = {
  data: CreateSupplier201
  status: 201
}

export type createSupplierResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createSupplierResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createSupplierResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createSupplierResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createSupplierResponseSuccess = (createSupplierResponse201) & {
  headers: Headers;
};
export type createSupplierResponseError = (createSupplierResponse400 | createSupplierResponse401 | createSupplierResponse403 | createSupplierResponse500) & {
  headers: Headers;
};

export type createSupplierResponse = (createSupplierResponseSuccess | createSupplierResponseError)

export const getCreateSupplierUrl = () => {




  return `/api/suppliers`
}

/**
 * Creates a new supplier. name, phone, email, address, and paymentType are required. Requires `create_supplier` permission.
 * @summary Create a supplier
 */
export const createSupplier = async (createSupplierRequest: CreateSupplierRequest, options?: RequestInit): Promise<createSupplierResponse> => {

  return customInstance<createSupplierResponse>(getCreateSupplierUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSupplierRequest)
  }
);}




export const getCreateSupplierMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSupplier>>, TError,{data: CreateSupplierRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createSupplier>>, TError,{data: CreateSupplierRequest}, TContext> => {

const mutationKey = ['createSupplier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSupplier>>, {data: CreateSupplierRequest}> = (props) => {
          const {data} = props ?? {};

          return  createSupplier(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof createSupplier>>>
    export type CreateSupplierMutationBody = CreateSupplierRequest
    export type CreateSupplierMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse

    /**
 * @summary Create a supplier
 */
export const useCreateSupplier = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSupplier>>, TError,{data: CreateSupplierRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSupplier>>,
        TError,
        {data: CreateSupplierRequest},
        TContext
      > => {
      return useMutation(getCreateSupplierMutationOptions(options), queryClient);
    }
    export type getSupplierByIdResponse200 = {
  data: GetSupplierById200
  status: 200
}

export type getSupplierByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getSupplierByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getSupplierByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getSupplierByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getSupplierByIdResponseSuccess = (getSupplierByIdResponse200) & {
  headers: Headers;
};
export type getSupplierByIdResponseError = (getSupplierByIdResponse401 | getSupplierByIdResponse403 | getSupplierByIdResponse404 | getSupplierByIdResponse500) & {
  headers: Headers;
};

export type getSupplierByIdResponse = (getSupplierByIdResponseSuccess | getSupplierByIdResponseError)

export const getGetSupplierByIdUrl = (id: string,) => {




  return `/api/suppliers/${id}`
}

/**
 * Retrieves a single supplier. Requires `view_supplier` permission.
 * @summary Get supplier by ID
 */
export const getSupplierById = async (id: string, options?: RequestInit): Promise<getSupplierByIdResponse> => {

  return customInstance<getSupplierByIdResponse>(getGetSupplierByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSupplierByIdQueryKey = (id: string,) => {
    return [
    `/api/suppliers/${id}`
    ] as const;
    }


export const getGetSupplierByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSupplierById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSupplierById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSupplierByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSupplierById>>> = ({ signal }) => getSupplierById(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSupplierById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSupplierByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSupplierById>>>
export type GetSupplierByIdQueryError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse


export function useGetSupplierById<TData = Awaited<ReturnType<typeof getSupplierById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSupplierById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSupplierById>>,
          TError,
          Awaited<ReturnType<typeof getSupplierById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSupplierById<TData = Awaited<ReturnType<typeof getSupplierById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSupplierById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSupplierById>>,
          TError,
          Awaited<ReturnType<typeof getSupplierById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSupplierById<TData = Awaited<ReturnType<typeof getSupplierById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSupplierById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get supplier by ID
 */

export function useGetSupplierById<TData = Awaited<ReturnType<typeof getSupplierById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSupplierById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSupplierByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateSupplierResponse200 = {
  data: UpdateSupplier200
  status: 200
}

export type updateSupplierResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateSupplierResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updateSupplierResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateSupplierResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateSupplierResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updateSupplierResponseSuccess = (updateSupplierResponse200) & {
  headers: Headers;
};
export type updateSupplierResponseError = (updateSupplierResponse400 | updateSupplierResponse401 | updateSupplierResponse403 | updateSupplierResponse404 | updateSupplierResponse500) & {
  headers: Headers;
};

export type updateSupplierResponse = (updateSupplierResponseSuccess | updateSupplierResponseError)

export const getUpdateSupplierUrl = (id: string,) => {




  return `/api/suppliers/${id}`
}

/**
 * Partially or fully updates a supplier. All fields are optional (only provided fields are updated). Requires `update_supplier` permission.
 * @summary Update a supplier
 */
export const updateSupplier = async (id: string,
    updateSupplierRequest: UpdateSupplierRequest, options?: RequestInit): Promise<updateSupplierResponse> => {

  return customInstance<updateSupplierResponse>(getUpdateSupplierUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSupplierRequest)
  }
);}




export const getUpdateSupplierMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSupplier>>, TError,{id: string;data: UpdateSupplierRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateSupplier>>, TError,{id: string;data: UpdateSupplierRequest}, TContext> => {

const mutationKey = ['updateSupplier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSupplier>>, {id: string;data: UpdateSupplierRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updateSupplier(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof updateSupplier>>>
    export type UpdateSupplierMutationBody = UpdateSupplierRequest
    export type UpdateSupplierMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Update a supplier
 */
export const useUpdateSupplier = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSupplier>>, TError,{id: string;data: UpdateSupplierRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSupplier>>,
        TError,
        {id: string;data: UpdateSupplierRequest},
        TContext
      > => {
      return useMutation(getUpdateSupplierMutationOptions(options), queryClient);
    }
    export type deleteSupplierResponse200 = {
  data: SuccessMessage
  status: 200
}

export type deleteSupplierResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteSupplierResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteSupplierResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteSupplierResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deleteSupplierResponseSuccess = (deleteSupplierResponse200) & {
  headers: Headers;
};
export type deleteSupplierResponseError = (deleteSupplierResponse401 | deleteSupplierResponse403 | deleteSupplierResponse404 | deleteSupplierResponse500) & {
  headers: Headers;
};

export type deleteSupplierResponse = (deleteSupplierResponseSuccess | deleteSupplierResponseError)

export const getDeleteSupplierUrl = (id: string,) => {




  return `/api/suppliers/${id}`
}

/**
 * Permanently deletes a supplier. Requires `delete_supplier` permission.
 * @summary Delete a supplier
 */
export const deleteSupplier = async (id: string, options?: RequestInit): Promise<deleteSupplierResponse> => {

  return customInstance<deleteSupplierResponse>(getDeleteSupplierUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSupplierMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSupplier>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteSupplier>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteSupplier'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSupplier>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteSupplier(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSupplierMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSupplier>>>

    export type DeleteSupplierMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a supplier
 */
export const useDeleteSupplier = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSupplier>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSupplier>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteSupplierMutationOptions(options), queryClient);
    }
    export type toggleSupplierStatusResponse200 = {
  data: ToggleSupplierStatus200
  status: 200
}

export type toggleSupplierStatusResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type toggleSupplierStatusResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type toggleSupplierStatusResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type toggleSupplierStatusResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type toggleSupplierStatusResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type toggleSupplierStatusResponseSuccess = (toggleSupplierStatusResponse200) & {
  headers: Headers;
};
export type toggleSupplierStatusResponseError = (toggleSupplierStatusResponse400 | toggleSupplierStatusResponse401 | toggleSupplierStatusResponse403 | toggleSupplierStatusResponse404 | toggleSupplierStatusResponse500) & {
  headers: Headers;
};

export type toggleSupplierStatusResponse = (toggleSupplierStatusResponseSuccess | toggleSupplierStatusResponseError)

export const getToggleSupplierStatusUrl = (id: string,) => {




  return `/api/suppliers/${id}/status`
}

/**
 * Sets the supplier status to 'active' or 'inactive'. Requires `update_supplier` permission.
 * @summary Toggle supplier status
 */
export const toggleSupplierStatus = async (id: string,
    toggleStatusRequest: ToggleStatusRequest, options?: RequestInit): Promise<toggleSupplierStatusResponse> => {

  return customInstance<toggleSupplierStatusResponse>(getToggleSupplierStatusUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(toggleStatusRequest)
  }
);}




export const getToggleSupplierStatusMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleSupplierStatus>>, TError,{id: string;data: ToggleStatusRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleSupplierStatus>>, TError,{id: string;data: ToggleStatusRequest}, TContext> => {

const mutationKey = ['toggleSupplierStatus'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleSupplierStatus>>, {id: string;data: ToggleStatusRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  toggleSupplierStatus(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ToggleSupplierStatusMutationResult = NonNullable<Awaited<ReturnType<typeof toggleSupplierStatus>>>
    export type ToggleSupplierStatusMutationBody = ToggleStatusRequest
    export type ToggleSupplierStatusMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Toggle supplier status
 */
export const useToggleSupplierStatus = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleSupplierStatus>>, TError,{id: string;data: ToggleStatusRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleSupplierStatus>>,
        TError,
        {id: string;data: ToggleStatusRequest},
        TContext
      > => {
      return useMutation(getToggleSupplierStatusMutationOptions(options), queryClient);
    }
