/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetNotifications200,
  InternalServerErrorResponse,
  MarkNotificationAsRead200,
  NotFoundResponse,
  SuccessMessage,
  UnauthorizedResponse
} from '../model';

import { customInstance } from '.././http';




export type getNotificationsResponse200 = {
  data: GetNotifications200
  status: 200
}

export type getNotificationsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getNotificationsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getNotificationsResponseSuccess = (getNotificationsResponse200) & {
  headers: Headers;
};
export type getNotificationsResponseError = (getNotificationsResponse401 | getNotificationsResponse500) & {
  headers: Headers;
};

export type getNotificationsResponse = (getNotificationsResponseSuccess | getNotificationsResponseError)

export const getGetNotificationsUrl = () => {




  return `/api/notifications`
}

/**
 * Returns all notifications for the current user (user-specific + global). Sorted by creation date descending. Authentication required.
 * @summary Get notifications
 */
export const getNotifications = async ( options?: RequestInit): Promise<getNotificationsResponse> => {

  return customInstance<getNotificationsResponse>(getGetNotificationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetNotificationsQueryKey = () => {
    return [
    `/api/notifications`
    ] as const;
    }


export const getGetNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof getNotifications>>, TError = UnauthorizedResponse | InternalServerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNotificationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNotifications>>> = ({ signal }) => getNotifications({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof getNotifications>>>
export type GetNotificationsQueryError = UnauthorizedResponse | InternalServerErrorResponse


export function useGetNotifications<TData = Awaited<ReturnType<typeof getNotifications>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotifications<TData = Awaited<ReturnType<typeof getNotifications>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNotifications>>,
          TError,
          Awaited<ReturnType<typeof getNotifications>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNotifications<TData = Awaited<ReturnType<typeof getNotifications>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get notifications
 */

export function useGetNotifications<TData = Awaited<ReturnType<typeof getNotifications>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNotifications>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNotificationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type markAllNotificationsAsReadResponse200 = {
  data: SuccessMessage
  status: 200
}

export type markAllNotificationsAsReadResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type markAllNotificationsAsReadResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type markAllNotificationsAsReadResponseSuccess = (markAllNotificationsAsReadResponse200) & {
  headers: Headers;
};
export type markAllNotificationsAsReadResponseError = (markAllNotificationsAsReadResponse401 | markAllNotificationsAsReadResponse500) & {
  headers: Headers;
};

export type markAllNotificationsAsReadResponse = (markAllNotificationsAsReadResponseSuccess | markAllNotificationsAsReadResponseError)

export const getMarkAllNotificationsAsReadUrl = () => {




  return `/api/notifications/read-all`
}

/**
 * Marks all of the current user's notifications (including global ones) as read. Authentication required.
 * @summary Mark all notifications as read
 */
export const markAllNotificationsAsRead = async ( options?: RequestInit): Promise<markAllNotificationsAsReadResponse> => {

  return customInstance<markAllNotificationsAsReadResponse>(getMarkAllNotificationsAsReadUrl(),
  {
    ...options,
    method: 'PATCH'


  }
);}




export const getMarkAllNotificationsAsReadMutationOptions = <TError = UnauthorizedResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsAsRead>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsAsRead>>, TError,void, TContext> => {

const mutationKey = ['markAllNotificationsAsRead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markAllNotificationsAsRead>>, void> = () => {


          return  markAllNotificationsAsRead()
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkAllNotificationsAsReadMutationResult = NonNullable<Awaited<ReturnType<typeof markAllNotificationsAsRead>>>

    export type MarkAllNotificationsAsReadMutationError = UnauthorizedResponse | InternalServerErrorResponse

    /**
 * @summary Mark all notifications as read
 */
export const useMarkAllNotificationsAsRead = <TError = UnauthorizedResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsAsRead>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markAllNotificationsAsRead>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getMarkAllNotificationsAsReadMutationOptions(options), queryClient);
    }
    export type markNotificationAsReadResponse200 = {
  data: MarkNotificationAsRead200
  status: 200
}

export type markNotificationAsReadResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type markNotificationAsReadResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type markNotificationAsReadResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type markNotificationAsReadResponseSuccess = (markNotificationAsReadResponse200) & {
  headers: Headers;
};
export type markNotificationAsReadResponseError = (markNotificationAsReadResponse401 | markNotificationAsReadResponse404 | markNotificationAsReadResponse500) & {
  headers: Headers;
};

export type markNotificationAsReadResponse = (markNotificationAsReadResponseSuccess | markNotificationAsReadResponseError)

export const getMarkNotificationAsReadUrl = (id: string,) => {




  return `/api/notifications/${id}/read`
}

/**
 * Marks a single notification as read by its ID. Authentication required.
 * @summary Mark notification as read
 */
export const markNotificationAsRead = async (id: string, options?: RequestInit): Promise<markNotificationAsReadResponse> => {

  return customInstance<markNotificationAsReadResponse>(getMarkNotificationAsReadUrl(id),
  {
    ...options,
    method: 'PATCH'


  }
);}




export const getMarkNotificationAsReadMutationOptions = <TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationAsRead>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof markNotificationAsRead>>, TError,{id: string}, TContext> => {

const mutationKey = ['markNotificationAsRead'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markNotificationAsRead>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  markNotificationAsRead(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkNotificationAsReadMutationResult = NonNullable<Awaited<ReturnType<typeof markNotificationAsRead>>>

    export type MarkNotificationAsReadMutationError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Mark notification as read
 */
export const useMarkNotificationAsRead = <TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationAsRead>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markNotificationAsRead>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getMarkNotificationAsReadMutationOptions(options), queryClient);
    }
    export type deleteNotificationResponse200 = {
  data: SuccessMessage
  status: 200
}

export type deleteNotificationResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deleteNotificationResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteNotificationResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deleteNotificationResponseSuccess = (deleteNotificationResponse200) & {
  headers: Headers;
};
export type deleteNotificationResponseError = (deleteNotificationResponse401 | deleteNotificationResponse404 | deleteNotificationResponse500) & {
  headers: Headers;
};

export type deleteNotificationResponse = (deleteNotificationResponseSuccess | deleteNotificationResponseError)

export const getDeleteNotificationUrl = (id: string,) => {




  return `/api/notifications/${id}`
}

/**
 * Permanently deletes a single notification. Authentication required.
 * @summary Delete a notification
 */
export const deleteNotification = async (id: string, options?: RequestInit): Promise<deleteNotificationResponse> => {

  return customInstance<deleteNotificationResponse>(getDeleteNotificationUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteNotificationMutationOptions = <TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteNotification'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNotification>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteNotification(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNotification>>>

    export type DeleteNotificationMutationError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a notification
 */
export const useDeleteNotification = <TError = UnauthorizedResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNotification>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteNotificationMutationOptions(options), queryClient);
    }
