/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BadRequestResponse,
  CreatePurchase201,
  CreatePurchaseRequest,
  ForbiddenResponse,
  GetPurchaseById200,
  GetPurchases200,
  GetPurchasesParams,
  InternalServerErrorResponse,
  NotFoundResponse,
  SuccessMessage,
  UnauthorizedResponse,
  UpdatePurchase200,
  UpdatePurchaseRequest
} from '../model';

import { customInstance } from '.././http';




export type getPurchasesResponse200 = {
  data: GetPurchases200
  status: 200
}

export type getPurchasesResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getPurchasesResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getPurchasesResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getPurchasesResponseSuccess = (getPurchasesResponse200) & {
  headers: Headers;
};
export type getPurchasesResponseError = (getPurchasesResponse401 | getPurchasesResponse403 | getPurchasesResponse500) & {
  headers: Headers;
};

export type getPurchasesResponse = (getPurchasesResponseSuccess | getPurchasesResponseError)

export const getGetPurchasesUrl = (params?: GetPurchasesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/purchases?${stringifiedParams}` : `/api/purchases`
}

/**
 * Returns a paginated list of purchase orders. Uses aggregation pipeline to populate supplier name for searching. Filterable by paymentStatus. Sorted by purchaseDate descending. Requires `view_purchase` permission.
 * @summary List purchase orders
 */
export const getPurchases = async (params?: GetPurchasesParams, options?: RequestInit): Promise<getPurchasesResponse> => {

  return customInstance<getPurchasesResponse>(getGetPurchasesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPurchasesQueryKey = (params?: GetPurchasesParams,) => {
    return [
    `/api/purchases`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetPurchasesQueryOptions = <TData = Awaited<ReturnType<typeof getPurchases>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(params?: GetPurchasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchases>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPurchasesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPurchases>>> = ({ signal }) => getPurchases(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPurchases>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPurchasesQueryResult = NonNullable<Awaited<ReturnType<typeof getPurchases>>>
export type GetPurchasesQueryError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse


export function useGetPurchases<TData = Awaited<ReturnType<typeof getPurchases>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params: undefined |  GetPurchasesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchases>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPurchases>>,
          TError,
          Awaited<ReturnType<typeof getPurchases>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPurchases<TData = Awaited<ReturnType<typeof getPurchases>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetPurchasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchases>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPurchases>>,
          TError,
          Awaited<ReturnType<typeof getPurchases>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPurchases<TData = Awaited<ReturnType<typeof getPurchases>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetPurchasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchases>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List purchase orders
 */

export function useGetPurchases<TData = Awaited<ReturnType<typeof getPurchases>>, TError = UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse>(
 params?: GetPurchasesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchases>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPurchasesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createPurchaseResponse201 = {
  data: CreatePurchase201
  status: 201
}

export type createPurchaseResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createPurchaseResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type createPurchaseResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createPurchaseResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type createPurchaseResponseSuccess = (createPurchaseResponse201) & {
  headers: Headers;
};
export type createPurchaseResponseError = (createPurchaseResponse400 | createPurchaseResponse401 | createPurchaseResponse403 | createPurchaseResponse500) & {
  headers: Headers;
};

export type createPurchaseResponse = (createPurchaseResponseSuccess | createPurchaseResponseError)

export const getCreatePurchaseUrl = () => {




  return `/api/purchases`
}

/**
 * Creates a new purchase order. Automatically calculates subtotals and totalAmount. Increments stock quantity for each medicine in the items array. Requires `create_purchase` permission.
 * @summary Create a purchase order
 */
export const createPurchase = async (createPurchaseRequest: CreatePurchaseRequest, options?: RequestInit): Promise<createPurchaseResponse> => {

  return customInstance<createPurchaseResponse>(getCreatePurchaseUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createPurchaseRequest)
  }
);}




export const getCreatePurchaseMutationOptions = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPurchase>>, TError,{data: CreatePurchaseRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createPurchase>>, TError,{data: CreatePurchaseRequest}, TContext> => {

const mutationKey = ['createPurchase'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createPurchase>>, {data: CreatePurchaseRequest}> = (props) => {
          const {data} = props ?? {};

          return  createPurchase(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreatePurchaseMutationResult = NonNullable<Awaited<ReturnType<typeof createPurchase>>>
    export type CreatePurchaseMutationBody = CreatePurchaseRequest
    export type CreatePurchaseMutationError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse

    /**
 * @summary Create a purchase order
 */
export const useCreatePurchase = <TError = BadRequestResponse | UnauthorizedResponse | ForbiddenResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createPurchase>>, TError,{data: CreatePurchaseRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createPurchase>>,
        TError,
        {data: CreatePurchaseRequest},
        TContext
      > => {
      return useMutation(getCreatePurchaseMutationOptions(options), queryClient);
    }
    export type getPurchaseByIdResponse200 = {
  data: GetPurchaseById200
  status: 200
}

export type getPurchaseByIdResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getPurchaseByIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getPurchaseByIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getPurchaseByIdResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getPurchaseByIdResponseSuccess = (getPurchaseByIdResponse200) & {
  headers: Headers;
};
export type getPurchaseByIdResponseError = (getPurchaseByIdResponse401 | getPurchaseByIdResponse403 | getPurchaseByIdResponse404 | getPurchaseByIdResponse500) & {
  headers: Headers;
};

export type getPurchaseByIdResponse = (getPurchaseByIdResponseSuccess | getPurchaseByIdResponseError)

export const getGetPurchaseByIdUrl = (id: string,) => {




  return `/api/purchases/${id}`
}

/**
 * Retrieves a single purchase order with populated supplier (name, phone, email) and populated product details (name, category) for each item. Requires `view_purchase` permission.
 * @summary Get purchase by ID
 */
export const getPurchaseById = async (id: string, options?: RequestInit): Promise<getPurchaseByIdResponse> => {

  return customInstance<getPurchaseByIdResponse>(getGetPurchaseByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetPurchaseByIdQueryKey = (id: string,) => {
    return [
    `/api/purchases/${id}`
    ] as const;
    }


export const getGetPurchaseByIdQueryOptions = <TData = Awaited<ReturnType<typeof getPurchaseById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPurchaseByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPurchaseById>>> = ({ signal }) => getPurchaseById(id, { signal });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPurchaseById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPurchaseByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getPurchaseById>>>
export type GetPurchaseByIdQueryError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse


export function useGetPurchaseById<TData = Awaited<ReturnType<typeof getPurchaseById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPurchaseById>>,
          TError,
          Awaited<ReturnType<typeof getPurchaseById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPurchaseById<TData = Awaited<ReturnType<typeof getPurchaseById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPurchaseById>>,
          TError,
          Awaited<ReturnType<typeof getPurchaseById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPurchaseById<TData = Awaited<ReturnType<typeof getPurchaseById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get purchase by ID
 */

export function useGetPurchaseById<TData = Awaited<ReturnType<typeof getPurchaseById>>, TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPurchaseById>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPurchaseByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updatePurchaseResponse200 = {
  data: UpdatePurchase200
  status: 200
}

export type updatePurchaseResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type updatePurchaseResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updatePurchaseResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updatePurchaseResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type updatePurchaseResponseSuccess = (updatePurchaseResponse200) & {
  headers: Headers;
};
export type updatePurchaseResponseError = (updatePurchaseResponse401 | updatePurchaseResponse403 | updatePurchaseResponse404 | updatePurchaseResponse500) & {
  headers: Headers;
};

export type updatePurchaseResponse = (updatePurchaseResponseSuccess | updatePurchaseResponseError)

export const getUpdatePurchaseUrl = (id: string,) => {




  return `/api/purchases/${id}`
}

/**
 * Updates a purchase order. Reverses old stock changes then applies new stock increments based on the updated items. Totals are recalculated automatically. Requires `update_purchase` permission.
 * @summary Update a purchase order
 */
export const updatePurchase = async (id: string,
    updatePurchaseRequest: UpdatePurchaseRequest, options?: RequestInit): Promise<updatePurchaseResponse> => {

  return customInstance<updatePurchaseResponse>(getUpdatePurchaseUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updatePurchaseRequest)
  }
);}




export const getUpdatePurchaseMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePurchase>>, TError,{id: string;data: UpdatePurchaseRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updatePurchase>>, TError,{id: string;data: UpdatePurchaseRequest}, TContext> => {

const mutationKey = ['updatePurchase'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updatePurchase>>, {id: string;data: UpdatePurchaseRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  updatePurchase(id,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdatePurchaseMutationResult = NonNullable<Awaited<ReturnType<typeof updatePurchase>>>
    export type UpdatePurchaseMutationBody = UpdatePurchaseRequest
    export type UpdatePurchaseMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Update a purchase order
 */
export const useUpdatePurchase = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updatePurchase>>, TError,{id: string;data: UpdatePurchaseRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updatePurchase>>,
        TError,
        {id: string;data: UpdatePurchaseRequest},
        TContext
      > => {
      return useMutation(getUpdatePurchaseMutationOptions(options), queryClient);
    }
    export type deletePurchaseResponse200 = {
  data: SuccessMessage
  status: 200
}

export type deletePurchaseResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type deletePurchaseResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deletePurchaseResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deletePurchaseResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type deletePurchaseResponseSuccess = (deletePurchaseResponse200) & {
  headers: Headers;
};
export type deletePurchaseResponseError = (deletePurchaseResponse401 | deletePurchaseResponse403 | deletePurchaseResponse404 | deletePurchaseResponse500) & {
  headers: Headers;
};

export type deletePurchaseResponse = (deletePurchaseResponseSuccess | deletePurchaseResponseError)

export const getDeletePurchaseUrl = (id: string,) => {




  return `/api/purchases/${id}`
}

/**
 * Deletes a purchase and reverses all inventory stock increments associated with it. Requires `delete_purchase` permission.
 * @summary Delete a purchase order
 */
export const deletePurchase = async (id: string, options?: RequestInit): Promise<deletePurchaseResponse> => {

  return customInstance<deletePurchaseResponse>(getDeletePurchaseUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeletePurchaseMutationOptions = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePurchase>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deletePurchase>>, TError,{id: string}, TContext> => {

const mutationKey = ['deletePurchase'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePurchase>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deletePurchase(id,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePurchaseMutationResult = NonNullable<Awaited<ReturnType<typeof deletePurchase>>>

    export type DeletePurchaseMutationError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse

    /**
 * @summary Delete a purchase order
 */
export const useDeletePurchase = <TError = UnauthorizedResponse | ForbiddenResponse | NotFoundResponse | InternalServerErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePurchase>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePurchase>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeletePurchaseMutationOptions(options), queryClient);
    }
