/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import type { CreatePurchaseRequestPaymentStatus } from './createPurchaseRequestPaymentStatus';
import type { MongoId } from './mongoId';
import type { PurchaseItem } from './purchaseItem';

export interface CreatePurchaseRequest {
  invoiceNumber: string;
  supplierId: MongoId;
  /** @minItems 1 */
  items: PurchaseItem[];
  /** @minimum 0 */
  discount?: number;
  /** @minimum 0 */
  tax?: number;
  paymentStatus?: CreatePurchaseRequestPaymentStatus;
  purchaseDate?: string;
  notes?: string;
}
