/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */

export type CreateSaleRequestPaymentMethod = typeof CreateSaleRequestPaymentMethod[keyof typeof CreateSaleRequestPaymentMethod];


export const CreateSaleRequestPaymentMethod = {
  cash: 'cash',
  card: 'card',
  transfer: 'transfer',
  cheque: 'cheque',
  insurance: 'insurance',
  other: 'other',
} as const;
