/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */

export type GetPurchasesPaymentStatus = typeof GetPurchasesPaymentStatus[keyof typeof GetPurchasesPaymentStatus];


export const GetPurchasesPaymentStatus = {
  Paid: 'Paid',
  Partial: 'Partial',
  Unpaid: 'Unpaid',
  all: 'all',
} as const;
