/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import type { LimitParameter } from './limitParameter';
import type { PageParameter } from './pageParameter';
import type { SearchParameter } from './searchParameter';

export type GetSalesParams = {
/**
 * Full-text search string (case-insensitive regex)
 */
search?: SearchParameter;
/**
 * Page number (1-based)
 * @minimum 1
 */
page?: PageParameter;
/**
 * Number of results per page
 * @minimum 1
 * @maximum 100
 */
limit?: LimitParameter;
};
