/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */

export type Permission = typeof Permission[keyof typeof Permission];


export const Permission = {
  view_dashboard: 'view_dashboard',
  view_store: 'view_store',
  create_store: 'create_store',
  update_store: 'update_store',
  delete_store: 'delete_store',
  view_category: 'view_category',
  create_category: 'create_category',
  update_category: 'update_category',
  delete_category: 'delete_category',
  view_supplier: 'view_supplier',
  create_supplier: 'create_supplier',
  update_supplier: 'update_supplier',
  delete_supplier: 'delete_supplier',
  view_sale: 'view_sale',
  create_sale: 'create_sale',
  update_sale: 'update_sale',
  delete_sale: 'delete_sale',
  view_profile: 'view_profile',
  update_profile: 'update_profile',
  view_users: 'view_users',
  create_user: 'create_user',
  update_user: 'update_user',
  delete_user: 'delete_user',
  view_purchase: 'view_purchase',
  create_purchase: 'create_purchase',
  update_purchase: 'update_purchase',
  delete_purchase: 'delete_purchase',
  view_report: 'view_report',
  create_report: 'create_report',
  update_report: 'update_report',
  delete_report: 'delete_report',
  view_customer: 'view_customer',
  create_customer: 'create_customer',
  update_customer: 'update_customer',
  delete_customer: 'delete_customer',
} as const;
