/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import type { MongoId } from './mongoId';
import type { ReportCreatedBy } from './reportCreatedBy';
import type { ReportDateRange } from './reportDateRange';
import type { ReportStatus } from './reportStatus';
import type { ReportType } from './reportType';
import type { Timestamps } from './timestamps';

export type Report = Timestamps & {
  _id?: MongoId;
  title?: string;
  type?: ReportType;
  description?: string;
  status?: ReportStatus;
  dateRange?: ReportDateRange;
  createdBy?: ReportCreatedBy;
};
