/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import type { MongoId } from './mongoId';
import type { SalePaymentMethod } from './salePaymentMethod';
import type { Timestamps } from './timestamps';

export type Sale = Timestamps & {
  _id?: MongoId;
  invoiceNumber?: string;
  date?: string;
  customerName?: string;
  medicineName?: string;
  /** @minimum 1 */
  quantity?: number;
  /** @minimum 0 */
  unitPrice?: number;
  /** @minimum 0 */
  total?: number;
  paymentMethod?: SalePaymentMethod;
};
