/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import type { LowStockItem } from './lowStockItem';
import type { Sale } from './sale';

export type StatsResponseData = {
  /** Total revenue this calendar month */
  totalRevenue?: number;
  /** Month-over-month revenue change percentage */
  revenueChange?: number;
  revenueLastMonth?: number;
  /** Number of sales created today */
  salesToday?: number;
  totalMedicines?: number;
  outOfStockCount?: number;
  /** Medicines with 0 < quantity < 20 */
  lowStockCount?: number;
  totalSuppliers?: number;
  totalUsers?: number;
  /** @maxItems 5 */
  recentSales?: Sale[];
  /** @maxItems 5 */
  lowStockItems?: LowStockItem[];
};
