/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCustomerRequestStatus } from './updateCustomerRequestStatus';

export interface UpdateCustomerRequest {
  name?: string;
  phone?: string;
  email?: string;
  address?: string;
  notes?: string;
  status?: UpdateCustomerRequestStatus;
  /** @minimum 0 */
  outstandingBalance?: number;
  isVIP?: boolean;
  lastVisit?: string;
}
