/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import type { MongoId } from './mongoId';
import type { PurchaseItem } from './purchaseItem';
import type { UpdatePurchaseRequestPaymentStatus } from './updatePurchaseRequestPaymentStatus';

/**
 * All fields optional. Stock is reversed for old items and reapplied for new items.
 */
export interface UpdatePurchaseRequest {
  invoiceNumber?: string;
  supplierId?: MongoId;
  /** @minItems 1 */
  items?: PurchaseItem[];
  /** @minimum 0 */
  discount?: number;
  /** @minimum 0 */
  tax?: number;
  paymentStatus?: UpdatePurchaseRequestPaymentStatus;
  purchaseDate?: string;
  notes?: string;
}
