/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import type { MongoId } from './mongoId';
import type { Permission } from './permission';
import type { Timestamps } from './timestamps';
import type { UserRole } from './userRole';

export type User = Timestamps & {
  _id?: MongoId;
  name?: string;
  email?: string;
  /** Cloudinary avatar URL */
  image?: string;
  role?: UserRole;
  permissions?: Permission[];
  isActive?: boolean;
};
