/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Pharmacy Dashboard API
 * Complete REST API for the Pharmacy ERP Dashboard. Manages medicines inventory, sales, purchases, suppliers, customers, users, notifications, and reports. All protected endpoints require a Bearer JWT token obtained via POST /api/auth/login.
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InternalServerErrorResponse,
  StatsResponse,
  UnauthorizedResponse
} from '../model';

import { customInstance } from '.././http';




export type getStatsResponse200 = {
  data: StatsResponse
  status: 200
}

export type getStatsResponse401 = {
  data: UnauthorizedResponse
  status: 401
}

export type getStatsResponse500 = {
  data: InternalServerErrorResponse
  status: 500
}

export type getStatsResponseSuccess = (getStatsResponse200) & {
  headers: Headers;
};
export type getStatsResponseError = (getStatsResponse401 | getStatsResponse500) & {
  headers: Headers;
};

export type getStatsResponse = (getStatsResponseSuccess | getStatsResponseError)

export const getGetStatsUrl = () => {




  return `/api/stats`
}

/**
 * Returns a comprehensive set of KPIs for the dashboard: revenue (this month vs last month with % change), today's sales count, total medicines, out-of-stock count, low-stock count, total suppliers, total users, recent 5 sales, and top 5 low-stock items. Also asynchronously triggers the alerts check. Authentication required.
 * @summary Get dashboard statistics
 */
export const getStats = async ( options?: RequestInit): Promise<getStatsResponse> => {

  return customInstance<getStatsResponse>(getGetStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetStatsQueryKey = () => {
    return [
    `/api/stats`
    ] as const;
    }


export const getGetStatsQueryOptions = <TData = Awaited<ReturnType<typeof getStats>>, TError = UnauthorizedResponse | InternalServerErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStats>>> = ({ signal }) => getStats({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getStats>>>
export type GetStatsQueryError = UnauthorizedResponse | InternalServerErrorResponse


export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStats>>,
          TError,
          Awaited<ReturnType<typeof getStats>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get dashboard statistics
 */

export function useGetStats<TData = Awaited<ReturnType<typeof getStats>>, TError = UnauthorizedResponse | InternalServerErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStats>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






